//! This module is entirely auto-generated by `build.rs`.
//! Do not edit: changes will be overwritten on the next build.

include!(concat!(env!("OUT_DIR"), "/generated_common.rs"));
include!(concat!(env!("OUT_DIR"), "/generated_types.rs"));
include!(concat!(env!("OUT_DIR"), "/generated_functions.rs"));
include!(concat!(env!("OUT_DIR"), "/generated_enums.rs"));
